export const motivationalQuotes = [
  "Keep pushing, you&apos;re closer than you think.",
  "Success is not final; failure is not fatal.",
  "Small steps every day lead to big results.",
  "You&apos;re doing great — stay consistent.",
  "Trust the process and keep applying.",
  "Every rejection is a step closer to the right job.",
  "Progress, not perfection.",
  "You&apos;re capable of amazing things.",
  "Action is the foundational key to all success.",
  "Stay hungry, stay foolish.",
  "Believe you can, and you&apos;re halfway there.",
  "Your future is created by what you do today.",
  "Push yourself, because no one else is going to do it for you.",
  "Don&apos;t watch the clock; do what it does — keep going.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Dream big. Work hard. Make it happen.",
  "The harder you work for something, the greater you&rsquo;ll feel when you achieve it.",
  "Opportunities don&rsquo;t happen. You create them.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "You don&apos;t have to be great to start, but you have to start to be great.",
];